config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts
  resources :posts do
  	resources :comments
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_attached_file :image, styles: { xlarge: "1400x1400>", large: "600x600>", medium: "300x300#", small: "150x150#", thumb: "100x100#" },
                    default_url: "/images/:style/missing.png",
                    :convert_options => { :all => "-quality 75 -strip" },
                    :storage => :s3,
                    :bucket => "kameron-blog"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  before_post_process :check_file_size

  enum categories: {
    "Music" => 1,
    "Think Pieces" => 2,
    "Style" => 3,
    "Written Works" => 4,
    "Album Reviews" => 5
  }

  def next(post)
    Post.where('id < ?', post.id).last
  end

  def first(post)
    if (post)
      Post.where('id > ?', post.id).first
    else
      Post.all.order("created_at").last
    end
  end

  def check_file_size
    valid?
    errors[:image_file_size].blank?
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?
  has_attached_file :avatar, styles: { large: "600x600", medium: "300x300", thumb: "150x150#" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:comment))
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if params[:category]
      @posts = Post.where(:category => params[:category])
    else
      @posts = Post.all.order("created_at DESC")
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :category, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.comment %></p>

<%= link_to "Delete", [comment.post, comment],
                      method: :delete, class: "btn btn-primary",
                      data: { confirm: 'Are you sure?'} %>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
  <%= f.input :comment, input_html: { class: 'textarea' }, wrapper: false, label_html: {class: 'label' } %>
  <%= f.button :submit, 'Leave a Reply', class: 'button is-primary' %>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
    <li><%= link_to 'Posts', posts_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<p id="trigger-overlay">Menu</p>
<div class="overlay overlay-contentpush">
	<button type="button" class="overlay-close">Close</button>
	<nav>
		<ul>
			<li><%= link_to 'Home', root_path %></li>
			<%= render 'layouts/navigation_links' %>
			<%= render 'layouts/nav_links_for_auth' %>
		</ul>
	</nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><span><%= link_to 'About', page_path('about') %></span></li>
<li><span><%= link_to "Work", posts_path %></span></li>
<li><span><%= link_to "Freelance", page_path('freelance') %></span></li>
<li><span><%= link_to "Anchor", page_path('anchor') %></span></li>
<li><span><%= link_to "Resume", page_path('resume') %></span></li>
<li><span><%= link_to "Contact", page_path('contact') %></span></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Official Website for Kameron Hay" %></title>
    <meta name="turbolinks-cache-control" content="no-cache">
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Official Website for Kameron Hay" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700,900,900i" rel="stylesheet">
  </head>
  <body class="<%= controller.controller_name %>">
    <header id="nav">
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" class="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About Kameron<% end %>
<h1 class="page-title">About Me</h1>
<hr class="header-hr"/>
<div class="container">
  <!-- row-start -->
  <div class="row">
    <%= image_tag("kam1.jpg",  id: "header-img")%>
    <div id="header-box" class="col-md-offset-3 col-md-7">
      <h1>Kameron Hay</h1>
      <h5>Kameron is a forward thinking and engaging multimedia journalist who excels at providing throught provoking material.</h5>
    </div>
  </div>
  <!-- row-end -->

  <!-- row-start -->
  <div class="row">
    <%= image_tag("kam2.jpg", id: "body-img") %>
    <div class="col-md-9 col-sm-7 text-center" id="more-box">
      <h3>More About Kameron</h3>
      <p>Kameron is a forward thinking and engaging multimedia journalist who
        excels at providing thought provoking material. Kameron has done freelance
        work for Bay Area music site Mixologi.com covering album reviews while
        also producing content on the latest trends and stories in pop culture.
        He has interned for New Orleans based hip hop and culture publication
        Shive Magazine while also overseeing his own music blog site kamhay.com.
        While attending Loyola University New Orleans he was a staff writer for
        the university’s award winning Maroon Newspaper. He is well versed in all
        forms of social media, writing, and video editing. He also has experience
        using applications such as Photoshop, Final Cut Pro, Avid, and Microsoft.
        Kameron is a member of the National Association of Black Journalists Student
        Task Force as well. Kameron’s goals in life are to write for magazines and
        websites such as Complex, XXL Magazine, ESPN’s The Undefeated, Spin and
        other sites or publications with similar focuses. Being an on air personality
        is also a goal of his.
      </p>
    </div>
  </div>
  <!-- row-end -->

  <!-- row-start -->
  <div class="row" id="last-about-row">
    <%= image_tag("stuartscott.jpg", id: "inspiration__img") %>
    <h1>Inspirations</h1>
    <div class="col-md-9 col-sm-7 text-center" id="inspiration__box">
      <h3>I am obsessed with fashion and sneakers
      I’m a huge hip hop enthusiast
      People That Inspire Me:</h3>
      <ul>
        <li>Marvin and Tracy Hay</li>
        <li>Kanye West</li>
        <li>Marc Spears</li>
        <li>Pierce Simpson</li>
        <li>Rob Markman</li>
        <li>Sway Calloway</li>
        <li>Joe La Puma</li>
        <li>StuartScott</li>
        <li>Bomani Jones</li>
        <li>Elliot Wilson</li>
      </ul>
    </div>
  </div>
  <div class="row text-center">
    <%= link_to(posts_path) do %>
      <div class="col-md-9 col-sm-7 text-center btn btn-primary" id="posts__link">
        <h3>Check out my work</h3>
      </div>
    <% end %>
  </div>
  <!-- row-end -->

</div>

app/views/pages/anchor.html.erb
<% content_for :title do %>Kameron's Anchor Footage<% end %>
<h1 class="page-title">Anchor Footage</h1>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
  <p>Here is footage of me anchoring the Uptown Howl and the Maroon Minute for Loyola News Services.</p>
  <div class="grid">
    <div class="grid-sizer">
      <div class="grid-item">
        <iframe src="https://player.vimeo.com/video/212825676" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
      </div>
      <div class="grid-item">
        <iframe src="https://player.vimeo.com/video/208710566" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
      </div>
      <div class="grid-item">
        <iframe src="https://player.vimeo.com/video/210840327" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
      </div>
    </div>
  </div>
</div>

app/views/pages/blogpost.html.erb
<!-- Page Content -->
<div class="container">

<div class="row">

    <!-- Blog Post Content Column -->
    <div class="col-lg-8">

        <!-- Blog Post -->

        <!-- Title -->
        <h1>Blog Post Title</h1>

        <!-- Author -->
        <p class="lead">
            by <a href="#">Start Bootstrap</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p><span class="glyphicon glyphicon-time"></span> Posted on August 24, 2013 at 9:00 PM</p>

        <hr>

        <!-- Preview Image -->
        <img class="img-responsive" src="http://placehold.it/900x300" alt="">

        <hr>

        <!-- Post Content -->
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

        <hr>

        <!-- Blog Comments -->

        <!-- Comments Form -->
        <div class="well">
            <h4>Leave a Comment:</h4>
            <form role="form">
                <div class="form-group">
                    <textarea class="form-control" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>

        <hr>

        <!-- Posted Comments -->

        <!-- Comment -->
        <div class="media">
            <a class="pull-left" href="#">
                <img class="media-object" src="http://placehold.it/64x64" alt="">
            </a>
            <div class="media-body">
                <h4 class="media-heading">Start Bootstrap
                    <small>August 25, 2014 at 9:30 PM</small>
                </h4>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
        </div>

        <!-- Comment -->
        <div class="media">
            <a class="pull-left" href="#">
                <img class="media-object" src="http://placehold.it/64x64" alt="">
            </a>
            <div class="media-body">
                <h4 class="media-heading">Start Bootstrap
                    <small>August 25, 2014 at 9:30 PM</small>
                </h4>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                <!-- Nested Comment -->
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="http://placehold.it/64x64" alt="">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Nested Start Bootstrap
                            <small>August 25, 2014 at 9:30 PM</small>
                        </h4>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                    </div>
                </div>
                <!-- End Nested Comment -->
            </div>
        </div>

    </div>

    <!-- Blog Sidebar Widgets Column -->
    <div class="col-md-4">

        <!-- Blog Search Well -->
        <div class="well">
            <h4>Blog Search</h4>
            <div class="input-group">
                <input type="text" class="form-control">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button">
                        <span class="glyphicon glyphicon-search"></span>
                </button>
                </span>
            </div>
            <!-- /.input-group -->
        </div>

        <!-- Blog Categories Well -->
        <div class="well">
            <h4>Blog Categories</h4>
            <div class="row">
                <div class="col-lg-6">
                    <ul class="list-unstyled">
                        <li><a href="#">Category Name</a>
                        </li>
                        <li><a href="#">Category Name</a>
                        </li>
                        <li><a href="#">Category Name</a>
                        </li>
                        <li><a href="#">Category Name</a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-6">
                    <ul class="list-unstyled">
                        <li><a href="#">Category Name</a>
                        </li>
                        <li><a href="#">Category Name</a>
                        </li>
                        <li><a href="#">Category Name</a>
                        </li>
                        <li><a href="#">Category Name</a>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- /.row -->
        </div>

        <!-- Side Widget Well -->
        <div class="well">
            <h4>Side Widget Well</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
        </div>

    </div>

</div>
<!-- /.row -->

<hr>

<!-- Footer -->
<footer>
    <div class="row">
        <div class="col-lg-12">
            <p>Copyright &copy; Your Website 2014</p>
        </div>
    </div>
    <!-- /.row -->
</footer>

app/views/pages/contact.html.erb
<h1 class="page-title">Contact Kameron</h1>
<p>You can contact me via email, phone, and social media</p>

<p>Email: kamantoine5@gmail.com</p>
<p>View my LinkedIn: <%= link_to "Here", "https://www.linkedin.com/in/kameron-hay-742112111/" %></p>

app/views/pages/freelance.html.erb
<% content_for :title do %>Kameron's Freelance Work<% end %>
<h1 class="page-title">Freelance Work</h1>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
  <p>These are links to previous work I have done for Shive Magazine, Bay Area based music site Mixologi, and the award winning Loyola University Maroon Newspaper.</p>
  <ul id="freelance__work">
    <li><%= link_to "Written Work @ Mixologi", "http://www.mixologi.com/author/kameronhay/" %></li>
    <li><%= link_to "Written Work @ Maroon", "http://www.loyolamaroon.com/staff/?writer=Kameron%20Hay" %></li>
    <li><%= link_to "Written Work @ Shive", "http://www.shivemagazine.com/author/kameron/" %></li>
  </ul>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, html: { multipart: true }) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>
  
  <div class="field">
    <%= form.label :body %>
    <%= form.cktext_area :body, id: :post_body, rows: 10 %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.select :category, Post.categories.keys,
                               id: :post_category,
                               prompt: "Select a Category" %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :post_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="page-title">Written Works</h1>
<div class="grid">
  <div class="grid-sizer">
    <div class="grid-item" id="brand">
      <h1>Kameron</h1>
      <p>Click a category on the right to filter by category.</p>
    </div>
    <div class="grid-item" id="categories">
      <h5>Categories:</h5>
      <ul class="categories">
        <li class="btn"><%= link_to "All", posts_path %></li>
        <li class="btn"><%= link_to "Music", posts_path(:category => "Music") %></li>
        <li class="btn"><%= link_to "Think Pieces", posts_path(:category => "Think Pieces") %></li>
        <li class="btn"><%= link_to "Style", posts_path(:category => "Style") %></li>
        <li class="btn"><%= link_to "Written Works", posts_path(:category => "Written Works") %></li>
        <li class="btn"><%= link_to "Album Reviews", posts_path(:category => "Album Reviews") %></li>
      </ul>
    </div>
    <% @posts.each do |post| %>
      <div class="grid-item">
        <%= link_to (image_tag post.image(:medium)), post %>
        <div class="overlay">
          <div class="title">
            <h3><%= truncate(post.title, length: 50) %></h3>
            <% if user_signed_in? %>
              <% if current_user.try(:admin?) %>
                <%= link_to 'Edit', edit_post_path(post), class: "admin__link" %>
                <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "admin__link destroy" %>
              <% end %>
            <% end %>
          </div>
          <%= link_to "Read More", post, class: "btn btn-primary" %>
      	</div>
      </div>
    <% end %>
  </div>
</div>

<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <%= link_to 'New Post', new_post_path %>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<article class="post">
  <div>
    <div class="absolute-bg" style="background-image: url('<%= @post.image(:xlarge) %>')">
      <%= link_to "All Work", posts_path,  id: "clip__link" %>
    </div>
  </div>
  <div class="post__container">
    <div>
      <span class="post__category"><%= @post.category %></span>
      <div class="post__content">
        <header>
          <time class="post__time"><%= @post.created_at %></time>
          <h1 class="post__header"><%= @post.title %></h1>
        </header>
        <p class="post__text"><%= raw @post.body %></p>
      </div>
      <div class="post__link">
        <% if @post.next(@post) %>
          <%= link_to "Next Post", @post.next(@post) %>
        <% elsif @post.first(@post) %>
          <%= link_to "First Post", @post.first(@previous) %>
        <% else %>
          <%= link_to "All Work", posts_path %>
        <% end %>
      </div>
    </div>
  </div>
</article>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<!-- Page Content -->
<div class="container">

    <div class="row" id="title">
      <div class="col-md-offset-1 col-md-8">
        <h1>Kameron Hay</h1>
        <p>Kameron is a forward thinking and engaging multimedia journalist who excels at providing throught provoking material.</p>
      </div>
      <div class="col-md-offset-1 col-md-6">
        <%= link_to "Read More", page_path("about"), class: "btn btn-primary" %>
      </div>
    </div>
    <!-- /.row -->
</div>
<!-- /.container -->